### ISSUE TITLE
Accessibility - Dataverse - Frames and Axecore

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#101]
## (Sample Page) Data For: Qualitative Data Sharing: Participant Understanding, Motivation, and Consent - Data - VandeVusee-Mueller_CognitiveInternviewConsentForm.pdf: https://data.qdr.syr.edu/file.xhtml?persistentId=doi:10.5064/F6YYA3O3/ID8HVJ&version=1.0

- [ ] Under Preview Tab (after you accept the terms), Document Preview Frame

**Comment by qqmyers** [comment]
It looks like fixing this issue would just let Axe test the iFrame in place. Since the previewer can render exactly the same HTML (with &preview=true in the URL), I think we can just test the previewer pages independently (they do have issues as with #103 for the spreadsheet viewer). If anyone has reason to believe that embedding as an iFrame can generate additional issues, I can look into adding the axe script which sounds look it would let Axe find issues when the previewer is shown as an iFrame.
