### ISSUE TITLE
Accessibility - Dataverse - ARIA Attributes and Valid Values

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#106]
### Add a New Data Project: https://data.qdr.syr.edu/dataset.xhtml?ownerId=1
- [ ] Title Box
- [ ] Subject Box
- [ ] Notes Box
- [ ] Depositor Box
- [ ] Deposit Date

**Comment by qqmyers** [comment]
These had some bad cut/paste with for= and aria-labelledBy= pointing to non-existent element ids. Now fixed.

Also: WRT to TESTING: - the code for showing the input fields for these had an odd 8-year old loop over 1 element in the xhtml code with a note that this prevented a 'weird' issue when using multiple values and the +/- buttons. I've removed that loop (which simplifies identifying the right label elements) and don't see any issues. IQSS doesn't remember what the issue was and I suspect it has been fixed since (aside from it being 8 years later, there's some indication that PrimeFaces did some work). In any case - testing should probably cover some basic add/remove for the plain text fields that allow multiple values.
