### ISSUE TITLE
Accessibility - Dataverse - ul and ol 

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#107]
### (Sample Page): Data for: Monster or Hero? Far-right Responses to Anders Behring Breivik and the 22 July Terrorist Attacks (https://data.qdr.syr.edu/dataset.xhtml?persistentId=doi:10.5064/F6MBCJ8M) 
- [ ] Download Dropdown Menu
![image](https://user-images.githubusercontent.com/89411909/138476846-d6046406-e841-446a-896c-f6c91e44d617.png)

**Comment by qqmyers** [comment]
I'm not seeing this one (I'm assuming this is from Axe?) although I think I'm on exactly the same dataset/file with the menu open. I'm on Windows looking at Chrome and Firefox. Checking the source, I don't see anything except li elements inside the ul for this menu and the data file citation submenu. There shouldn't have been any changes on prod  - since mid Sep. 

Can you confirm this still exists and provide more info on where you're seeing this? If it is still there, clicking on the inspect button (next to 'highlight') and sending a snapshot of that portion of the DOM tree would be helpful.

**Comment by adam3smith** [comment]
Also not seeing this. I'm guessing might be an installed add-on -- sometimes they insert DOM elements
