### ISSUE TITLE
Silent updates fail to update filenames

### ISSUE THREAD

**Issue by rdemgenski** [QualitativeDataRepository/dataverse#58]
Changing filenames of a published project and publishing regular version updates works as it should, but when executing silent update filenames revert to original. 

Recreated on stage (https://data.stage-aws-new.qdr.org/dataset.xhtml?persistentId=doi%3A10.33564%2FFK2FWWSZ6&version=DRAFT), "_test" successful with minor release, "_2" unsuccessful with silent update.

**Comment by qqmyers** [comment]
I've fixed this on dev - fwiw, my guess is that it was a consequence of the fix for handling deleted files, but it's a bit surprising that testing of that PR didn't catch it. In any case, I'd like to get the Drupal search changes done and then push a few fixes to stage at the same time (unless it's urgent to get this to stage).

**Comment by adam3smith** [comment]
No rush on this -- just let us know once you've pushed the updates to Stage

**Comment by adam3smith** [comment]
Fixed in latest release on prod
