### ISSUE TITLE
Accessibility - Heading Levels

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#86]
## Data Management Plan Checklist: https://qdr.syr.edu/guidance/managing/dmp-checklist 
- [x] "What personnel would work on the project?" (h3)

## Handling Sensitive Data: https://qdr.syr.edu/policies/sensitive-data 
- [x] "Special Deposit Agreement" (h3) 

## Formatting Data: https://qdr.syr.edu/guidance/managing/formatting-data
- [x] "Recommended Formats for Submission of Born-Digital Data Files" (h3)

## Preparing a Data Project: https://qdr.syr.edu/guidance/managing/preparing-data
- [x] "Data Files - Organizational Principles" (h3)

**Comment by qqmyers** [comment]
These look like cases where the issue is in the content of the Drupal pages (i.e. editable in the Drupal UI). If just switching, for example, from using h3 to h2 is not acceptable (i.e. because those elements are now too large/bold/etc.) I could add either some custom css to define h2 to match the current h3, or we could create a custom class (and the text would change to something like <h3> --> <p class="qdr-h3">) . 
Let me know what route you want and I'm happy to leave it alone, make the edits, and/or change the css as desired.

**Comment by adam3smith** [comment]
Let's start by making these changes ourselves (i.e. between Theresa, Michael Dessi, and me.) If something doesn't look right as a consequence, we'll circle back about CSS adjustments
